### ISSUE TITLE
block when stitch multi microscope tiles imges using m2stitch in terminal on Windows 10

### ISSUE THREAD

**Issue by zhusihan-python** [yfukai/m2stitch#133]
Mr Fukai:    
Hello from China.    
I am an engineer in hangzhou. I am developing a software for scanner confronting the problem of stitch images captured by micro camera. I found your project m2stitch in github yet have some problems while test the example. 
There is not much tutorials about this python lib. so i am seeking help from you.    
when i run the example it just block nothing happened, no errors 
![image](https://user-images.githubusercontent.com/23504604/143893884-86b82d3c-6555-43bf-a6f5-c73323b49e00.png)
here is my scripts
```
# coding: utf-8
import os
from os import path
import cv2
import numpy as np
import pandas as pd

import m2stitch

script_path = path.dirname(path.realpath(__file__))

image_file_path = r"F:\slide_data_bak\20211119_00005\1\captures\temp"
r = os.listdir(image_file_path)
print(r)
r_full = [os.path.join(image_file_path, f) for f in r if f.endswith("jpg") and len(f) <= 6]
print(r_full)

images = []

for img_path in r_full:
    img = cv2.imread(img_path)
    images.append(images)

props_file_path = r"F:\slide_data_bak\20211119_00005\1\captures\temp\testimages_props.csv"
# print(images)
# props_file_path = path.join(script_path, "../tests/data/testimages_props.csv")
# images = np.load(image_file_path)
props = pd.read_csv(props_file_path, index_col=0)
rows = props["row"].to_list()
cols = props["col"].to_list()

# print(images.shape)
# # must be 3-dim, with each dimension meaning (tile_index,x,y)
print(rows)
# # the row indices for each tile index. for example, [1,1,2,2,2,...]
print(cols)
# # the column indices for each tile index. for example, [2,3,1,2,3,...]

result_df, _ = m2stitch.stitch_images(images, rows, cols)

print(result_df["x_pos"])
# # the absolute x positions of the tiles
print(result_df["y_pos"])
# # the absolute y positions of the tiles

# # stitching example
result_df["x_pos2"] = result_df["x_pos"] - result_df["x_pos"].min()
result_df["y_pos2"] = result_df["y_pos"] - result_df["y_pos"].min()

size_x = images.shape[1]
size_y = images.shape[2]

stitched_image_size = (
    result_df["x_pos2"].max() + size_x,
    result_df["y_pos2"].max() + size_y,
)
stitched_image = np.zeros_like(images, shape=stitched_image_size)
for i, row in result_df.iterrows():
    stitched_image[
        row["x_pos2"] : row["x_pos2"] + size_x,
        row["y_pos2"] : row["y_pos2"] + size_y,
    ] = images[i]

result_image_file_path = path.join(script_path, "stitched_image.npy")
# np.save(result_image_file_path, stitched_image)
cv2.imwrite(result_image_file_path, stitched_image)
```
my image data is like this 
![image](https://user-images.githubusercontent.com/23504604/143893991-86914390-88ae-41e0-9856-22dd791a05ca.png)
csv config 
![image](https://user-images.githubusercontent.com/23504604/143894030-947ff821-88f7-45b0-b036-3d6afa766014.png)
my python version is python 3.9.0
 i wonder if this lib can be used to stitch several images if not a single npy file.   
 any help would be appreciated

**Comment by yfukai** [comment]
Thanks for the report! Yeah, it should work with files like that. I'll check if you're doing what the package expects. I'm sorry for the lack of detailed documentation/examples, as I have to use my time on another project for now... 
I'd like to know about one thing; If you check the Task Manager, do you find the CPU working for this, or not?

I think I should add something like:
- command line interface 
- logging for debugging 

by the way.

**Comment by zhusihan-python** [comment]
thank you for the reply.
i found an error in my code that the images  should be a numpy array, now its a list.
i change it to numpy array like this, 
`images = np.array(images )
`
and now it has output, get an error in this line
`result_df, _ = m2stitch.stitch_images(images, rows, cols)`
the error:
![image](https://user-images.githubusercontent.com/23504604/143971688-3b8c9427-0198-4003-ac02-99b9064682d5.png)
i think its the image data organized not expected by the package, i will update my progress if i found a way to fix it.

**Comment by yfukai** [comment]
Hi @zhusihan-python , I updated the input/output dimension for the sake of clarity. Still backward-compatible I believe but please check the [example](https://github.com/yfukai/m2stitch/blob/master/examples/stitching_example.py) if you feel like. That might be clearer than the original version.

The algorithm is also updated a bit for more robust parameter findings. I cannot take time for good documentation, but things may be clear from [API](https://m2stitch.readthedocs.io/en/latest/reference.html) or scripts in the `tests/` folder. 
Please try them if you would feel like!

**Comment by yfukai** [comment]
I think this may be closely related to #99 and close for now. Please get updated there, and feel free to open if you think this is still not solved @zhusihan-python!

**Comment by Greatuso** [comment]
Hi, I would like to ask for your advice Is the x and y deviation in the CSV file calculated or given by the hardware system?
