### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by HoukJangBNL** [yfukai/m2stitch#146]
Hi, I am trying to implement m2stitch to stitch my microscope image, but I got an error as following:
Can you provide some intuition to solve this problem?
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/var/folders/cq/4b_bv79d3mjgvjwtjl3qfbmc0000gn/T/ipykernel_88498/3576127480.py in <module>
----> 1 result_df1, _ = m2stitch.stitch_images(images, rows, cols)

/usr/local/lib/python3.9/site-packages/m2stitch/stitching.py in stitch_images(images, rows, cols, pou, overlap_prob_uniform_threshold, full_output)
    127     grid, r = compute_repeatability(grid, overlap_n, overlap_w, W, H, pou)
    128     grid = filter_by_repeatability(grid, r)
--> 129     grid = replace_invalid_translations(grid)
    130 
    131     grid = refine_translations(images, grid, r)

/usr/local/lib/python3.9/site-packages/m2stitch/_stage_model.py in replace_invalid_translations(grid)
    327         grid.loc[isna, f"{direction}_ncc_second"] = -1
    328     for direction, xy in itertools.product(["top", "left"], ["x", "y"]):
--> 329         assert np.all(np.isfinite(grid[f"{direction}_{xy}_second"]))
    330 
    331     return grid

AssertionError:

**Comment by yfukai** [comment]
I think this may be because of the same reason as #99 and close for now. Please feel free to open if you think this is still not solved @HoukJangBNL !
