### ISSUE TITLE
Stitched image in example is in strange format.

### ISSUE THREAD

**Issue by Fredpeperoni** [yfukai/m2stitch#278]
Hi! I am trying to use m2stitch and have a problem in example. Stitched image (as well as images from testimages.npy) has negative values in pixels, moreover they are in float16 format. How to visualize them? Are these values are standardized or something?

**Comment by Fredpeperoni** [comment]
I also have problems, when trying to stitch my own micriscopy images. Unfortunatelly, I am not well understood MIST implementation, so i am getting: _AssertionError: there is no good top pair_. What shoud I do to fix it?

**Comment by yfukai** [comment]
Hi thanks @Fredpeperoni for your comment! The stitch_images function will return the position of the tiles, and we need to stitch the image using that data. A simple example is shown in https://m2stitch.readthedocs.io/en/latest/usage.html . If you could paste the piece of code you're running, I might be able to help you more.

**Comment by yfukai** [comment]
Oh I guess you meant the [stitching_example.py](https://github.com/yfukai/m2stitch/blob/master/examples/stitching_example.py) ... Let me check it then.

**Comment by yfukai** [comment]
Hi, @Fredpeperoni ! I think I normalized the original image, and save it as `np.float16` to save some space in the repo... to visualize it, you have two options:
- using `matplotlib` :
```python
from matplotlib import pyplot as plt
plt.imshow(stitched_image)
```
- saving as a TIFF or something by `scikit-image`
```python
from skimage.io import imsave
imsave("stitched_image.tiff",stitched_image.astype(np.float32))
# visualize by your favorite viewer
```
I hope this helps!
