### ISSUE TITLE
Not able to stitch microscope images

### ISSUE THREAD

**Issue by kuldeep203** [yfukai/m2stitch#329]
can you tell me what is this props file path.
props_file_path = path.join(script_path, "/tests/data/testimages_props.csv")

**Comment by yfukai** [comment]
Hi thanks @kuldeep203 for your interest!
That is this file, https://github.com/yfukai/m2stitch/blob/master/tests/data/testimages_props.csv . 
What you actually need is the `col` and `row` lists.

**Comment by kuldeep203** [comment]
i dont know exactly it is. can you expain it in more details.

**Comment by yfukai** [comment]
The package assumes the images in a regular tile grid, and you need to give the positions of that grid to the 
 stitching function:
https://m2stitch.readthedocs.io/en/latest/reference.html#m2stitch.stitching.stitch_images
and at least you need to supply three arguments (copied from the doc)
- images (np.ndarray) – the images to stitch.
- rows (list, optional) – the row indices (tile position in the second last dimension) of the images.
- cols (list, optional) – the column indices (tile position in the last dimension) of the images

The file contains lists for the rows and cols, but you can just write them in your code.
Hope this helps!

**Comment by kuldeep203** [comment]
i can share you the images folder can you help to stitch all together so that i can get the basic concept.

**Comment by yfukai** [comment]
Sorry, but I'm afraid I can't take the time to help you to that extent... Please take a look at the documentation and try it by yourself. If you would like more GUI-oriented software, you might like to try the MIST the original implementation by NIST people https://pages.nist.gov/MIST/ .

**Comment by yfukai** [comment]
I hope I could have time to organize the documentation a bit more. I'm sorry for the inconvenience for now.

**Comment by kuldeep203** [comment]
I have run stitching_example and i run successfully but still not able to understand how you created testimages.npy testimages_props.csv. what data we need to calculate for making this file. please help me in this case as its very urgent in my current project.

**Comment by yfukai** [comment]
> how you created testimages.npy testimages_props.csv.

those files are created from microscopy images taken by a Zeiss microscope. Originally they were `*.czi` files and I parsed them to create those files.
I hope this helps!

**Comment by kuldeep203** [comment]
thanks for your answer can you send me that .czi file and second thing is that i am taking the picture with with our microscope which is also in r&d phase. suppose i have taken 10 images from digital microscope. now let me know i can stitch these images or how i can prepare csv file. is there anyway to run the code without cvs file.

**Comment by yfukai** [comment]
> can you send me that .czi file

Sorry but unfortunately, I cannot for now 

> let me know i can stitch these images or how i can prepare csv file

You can import them into python for example [aicsimageio](https://github.com/AllenCellModeling/aicsimageio).

> is there anyway to run the code without cvs file

Yes, you can supply the positions by hand

**Comment by yfukai** [comment]
How about trying https://pages.nist.gov/MIST/ or https://labsyspharm.github.io/ashlar/ ? Those can be used from command line and might fit your use case.

**Comment by kuldeep203** [comment]
can you send me the dataset of of images you have used in your  npy file.
