### ISSUE TITLE
no good top pair

### ISSUE THREAD

**Issue by Greatuso** [yfukai/m2stitch#431]
![image](https://github.com/yfukai/m2stitch/assets/47665698/e422bdde-dd73-4704-a3d6-8ea79848dea2)
![image](https://github.com/yfukai/m2stitch/assets/47665698/125d2325-0af4-4f90-8c36-7aa8b59046d8)
Hello, I would like to ask for your advice. As shown in the picture, it is my data and the reason for the error. I would like to know what caused this? Do I need to change the direction of the image?

Sincerely thank you！

**Comment by Greatuso** [comment]
This is my Python script. I have selected four images, 01, 02, 06, and 07, to form a 2 * 2 grid

`import os
import m2stitch
from skimage import io
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import cv2 as cv

# 获取指定目录下的所有.JPG文件
imagelist = [img for img in os.listdir(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data') if img.endswith('.jpg')]

for img in imagelist:
    path = r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\\' + img
    image = cv.imread(path)
    
    gray_image = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
  
    np.save(path.replace('.jpg', '.npy'), gray_image)


image1 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\01.npy')
image2 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\02.npy')
image3 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\06.npy')
image4 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\07.npy')


images = np.array([image2, image1, image4, image3])
# images = np.array([image1,image2])
print(images.shape)

cols=[0,1,0,1]
rows=[0,0,1,1]

result_df, _ = m2stitch.stitch_images(images, rows, cols, row_col_transpose=False, ncc_threshold=0.1)`

**Comment by Greatuso** [comment]
This is my Python script. I have selected four images, 01, 02, 06, and 07, to form a 2 * 2 grid：
```
import os
import m2stitch
from skimage import io
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import cv2 as cv
imagelist = [img for img in os.listdir(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data') if img.endswith('.jpg')]
for img in imagelist:
    path = r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\\' + img
    image = cv.imread(path)
    gray_image = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
    np.save(path.replace('.jpg', '.npy'), gray_image)
image1 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\01.npy')
image2 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\02.npy')
image3 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\06.npy')
image4 = np.load(r'C:\Users\14287\Desktop\Ashlar\m2stitch-master\tests\data\07.npy')
images = np.array([image2, image1, image4, image3])
print(images.shape)
cols=[0,1,0,1]
rows=[0,0,1,1]
result_df, _ = m2stitch.stitch_images(images, rows, cols, row_col_transpose=False, ncc_threshold=0.1)
```

**Comment by yfukai** [comment]
Hi @Greatuso, I suspect you selected wrong images! For me it looks like that the images are aligned in such a way that
```
01 02 
10 09
```
