### ISSUE TITLE
RuntimeWarning: invalid value encountered in scalar divide   return n / d

### ISSUE THREAD

**Issue by IgorShal** [yfukai/m2stitch#433]
"RuntimeWarning: invalid value encountered in scalar divide   return n / d" occurs in case n and d are equal to zero. Maybe it's not fatal, but usually big warning message scares me :D

**Comment by yfukai** [comment]
Hi, maybe you could do
```
import warnings 
warnings.simplefilter("ignore",RuntimeWarning)
```
