### ISSUE TITLE
non grid tiles ?

### ISSUE THREAD

**Issue by VolkerH** [yfukai/m2stitch#71]
The description says the method supports irregular shapes,
but it appears the tiles still need to be on a regular grid, correct?

I have an application where the tiles can be anywhere (not necessarily a `n_row` by `n_col` grid), but each tile is overlapping some other tile and I have stage coordinates. 

Can this use case be supported?

**Comment by yfukai** [comment]
Thank you for your comment! You're right, I'm afraid the term "irregular" was inacculate. It supports tiles with lacking positions, but they still need to be on a regular grid. I will fix the README (and the image.sc post).

**Comment by VolkerH** [comment]
Thanks for the clarification!
I had a look at the source code and from what I see with the directions "North", "East" and the way the tiles are traversed it would be quite a bit of effort to modify the code for arbitrary tile positions, but maybe I am wrong?

**Comment by yfukai** [comment]
Thanks, actually I followed the termination of the original paper, but agree with you in that it somehow makes it difficult to understand... I will make an issue for this problem (and hopefully refactor in the near future). 

Regarding the non-grid tiles, I think what we can do is skipping the validations that assume the equal tile overlaps (to make the estimation robust). We can still make use of some logic in the package, but we would need a bit more of work on aligning and so on.

**Comment by yfukai** [comment]
Reading the comments, I also noticed the terms `pos_x` and `pos_y` are not intuitive as they point to the row and column positions, respectively #74. It will be a breaking change, but I would like to also refactor this in the near future.

**Comment by jmuhlich** [comment]
@VolkerH I hope it's not bad form to suggest another tool here, but our [Ashlar](https://github.com/labsyspharm/ashlar) stitching tool (also written in Python) can handle arbitrary tile positions when you have stage coordinates that BioFormats can extract from your images (and even if you have the stage coordinates in some other format, that could be handled with just a few lines of new code). Ashlar was originally designed to handle stitching and registration together for cyclic imaging technologies, but we found the quality of stitching alone is comparable to MIST - see Figure 5A in our preprint at https://www.biorxiv.org/content/10.1101/2021.04.20.440625v1 . Please submit an issue on our GitHub repo or post on image.sc if you need help.

**Comment by jmuhlich** [comment]
Oh I see you already found Ashlar since you've got a fork on github! Anyway, please reach out for assistance! My email is in my profile if you prefer that.

**Comment by yfukai** [comment]
Hi @jmuhlich, thank you for your suggestion, hmm, I wish I could notice that tool before I wrote this tool! My intention is not competing with other tools, and I will check it out and see how I could do.

**Comment by yfukai** [comment]
I think it's fine to close this issue for now, but the terminology should be refactored #74 .
