### ISSUE TITLE
Error in imports

### ISSUE THREAD

**Issue by joaomamede** [yfukai/m2stitch#86]
AttributeError                            Traceback (most recent call last)
<ipython-input-2-c21e89cd684b> in <module>
      5 import matplotlib.pyplot as plt
      6 import sys
----> 7 import m2stitch
      8 sys.path.insert(0,'/home/jmamede/scripts')
      9 # from support_pla import othercolor, cell_mask, multiply, rebin

~/anaconda3/lib/python3.7/site-packages/m2stitch/__init__.py in <module>
      8 __email__ = "ysk@yfukai.net"
      9 
---> 10 from .stitching import stitch_images
     11 
     12 __all__ = ["stitch_images"]

~/anaconda3/lib/python3.7/site-packages/m2stitch/stitching.py in <module>
      9 from tqdm import tqdm
     10 
---> 11 from ._constrained_refinement import refine_translations
     12 from ._global_optimization import compute_final_position
     13 from ._global_optimization import compute_maximum_spanning_tree

~/anaconda3/lib/python3.7/site-packages/m2stitch/_constrained_refinement.py in <module>
      7 from tqdm import tqdm
      8 
----> 9 from ._translation_computation import extract_overlap_subregion
     10 from ._translation_computation import ncc
     11 from ._typing_utils import Float

~/anaconda3/lib/python3.7/site-packages/m2stitch/_translation_computation.py in <module>
      5 import numpy.typing as npt
      6 
----> 7 from ._typing_utils import Float
      8 from ._typing_utils import FloatArray
      9 from ._typing_utils import Int

~/anaconda3/lib/python3.7/site-packages/m2stitch/_typing_utils.py in <module>
      5 import numpy.typing as npt
      6 
----> 7 NumArray = npt.NDArray[Any]
      8 FloatArray = npt.NDArray[np.float_]
      9 

AttributeError: module 'numpy.typing' has no attribute 'NDArray'

**Comment by yfukai** [comment]
Thanks, hmm, looks like `numpy` version problem, can you update `numpy` to 1.21 or 1.20.3 for example?
Did you install the package from `pip`?  Maybe I should check the dependency.

**Comment by yfukai** [comment]
the output for `pip freeze` or `conda list` might be helpful to help you solve the problem.

**Comment by yfukai** [comment]
I confirmed this happens with `numpy=1.20.3` and updated the requirements, thanks @joaomamede for your report!

**Comment by yfukai** [comment]
`requirements.txt` seems to be still invalid

**Comment by yfukai** [comment]
Confirmed `numpy` update. 
@joaomamede , now you can try with: `pip install m2stitch==0.1.1`. Hopefully it works!

**Comment by joaomamede** [comment]
It imported well.
Thank you, I'll see if it implements stitching well for my files.
